# Generated by Django 4.2 on 2023-05-18 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='StudyingDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='StudyingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_student', models.CharField(max_length=70)),
                ('id_course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudyingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=400)),
                ('duties', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Studying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('level', models.CharField(max_length=70)),
                ('time', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=300)),
                ('participants', models.CharField(max_length=50)),
                ('programs_settings', models.CharField(max_length=500)),
                ('beginning', models.CharField(max_length=8)),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('studying_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_friendly.studyingdirection')),
                ('teacher', models.ManyToManyField(to='it_friendly.worker')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_friendly.studyingtype')),
            ],
        ),
    ]
