# Generated by Django 4.2 on 2023-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_friendly', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studyingstudent',
            constraint=models.UniqueConstraint(fields=('username_student', 'id_course'), name='unique_study_student'),
        ),
    ]
