# Generated by Django 4.2 on 2023-04-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('it_friendly', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('level', models.CharField(max_length=70)),
                ('time', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=300)),
                ('participants', models.CharField(max_length=50)),
                ('programs_settings', models.CharField(max_length=500)),
                ('beginning', models.DateTimeField()),
            ],
        ),
    ]
