# Generated by Django 4.2 on 2023-05-19 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('it_friendly', '0002_studyingstudent_unique_study_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyingstudent',
            name='id_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_friendly.studying'),
        ),
        migrations.AlterField(
            model_name='studyingstudent',
            name='username_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
