# Generated by Django 4.2 on 2023-05-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_friendly', '0004_courselevel_coursepricerange_coursetimingrange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studying',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='it_friendly.courselevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studying',
            name='price_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='it_friendly.coursepricerange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studying',
            name='timing_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='it_friendly.coursetimingrange'),
            preserve_default=False,
        ),
    ]
