# Generated by Django 4.2 on 2023-04-26 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('it_friendly', '0005_faq_studyingdirection_studyingtype_worker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('level', models.CharField(max_length=70)),
                ('time', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=300)),
                ('participants', models.CharField(max_length=50)),
                ('programs_settings', models.CharField(max_length=500)),
                ('beginning', models.DateTimeField()),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('studying_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_friendly.studyingdirection')),
                ('teacher', models.ManyToManyField(to='it_friendly.worker')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_friendly.studyingtype')),
            ],
        ),
    ]
